service: ${{values.name}}
configValidationMode: warn
frameworkVersion: '3.0.1'

provider:
  name: aws
  profile: juan
  runtime: nodejs18.x
  endpointType: REGIONAL
  apiName: "${self:service}-${self:custom.stage}-api"
  region: us-east-1
  memorySize: 128
  timeout: 10
  stage: ${opt:stage, 'staging'}

package:
  individually: true
  patterns:
    - "!*/**"

custom:
  stage: ${opt:stage, 'dev'}
  static_envs:
    prod: prod
    other: staging
  envtype: ${self:custom.static_envs.${opt:stage}, self:custom.static_envs.other}

functions:
  getHelloWord:
    handler: app.handler
    name: "${self:service}-${self:custom.stage}-hello-world"
    package:
      patterns:
        - "app.js"
    events:
      - http:
          path: /hello-world/
          method: get
